language: python

python:
- '2.7'

install:
    - pip install pytest
    - pip install pytest-cov

script:
    - py.test --cov . --cov model --cov tools --cov-config .coveragerc

after_success:
- pip install python-coveralls
- coveralls
